version = 1

[[annotations]]
path = "toxfile.py"
SPDX-FileCopyrightText = "Copyright (c) 2023 Masen Furer"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "**"
SPDX-FileCopyrightText = [
    "2022-2025 Stephen Arnold <stephen.arnold42@gmail.com>",
]
SPDX-License-Identifier = "LGPL-2.1-or-later"
